[2023-11-30T01:43:40.935+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lviv_weather.inject_data manual__2023-11-29T23:43:27.582078+00:00 [queued]>
[2023-11-30T01:43:40.945+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lviv_weather.inject_data manual__2023-11-29T23:43:27.582078+00:00 [queued]>
[2023-11-30T01:43:40.945+0200] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T01:43:40.956+0200] {taskinstance.py:1382} INFO - Executing <Task(SqliteOperator): inject_data> on 2023-11-29 23:43:27.582078+00:00
[2023-11-30T01:43:40.960+0200] {standard_task_runner.py:57} INFO - Started process 148653 to run task
[2023-11-30T01:43:40.963+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'lviv_weather', 'inject_data', 'manual__2023-11-29T23:43:27.582078+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/lviv_weather.py', '--cfg-path', '/tmp/tmp_g0jqf6a']
[2023-11-30T01:43:40.965+0200] {standard_task_runner.py:85} INFO - Job 47: Subtask inject_data
[2023-11-30T01:43:41.019+0200] {task_command.py:416} INFO - Running <TaskInstance: lviv_weather.inject_data manual__2023-11-29T23:43:27.582078+00:00 [running]> on host yurabd.
[2023-11-30T01:43:41.439+0200] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='lviv_weather' AIRFLOW_CTX_TASK_ID='inject_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T23:43:27.582078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-29T23:43:27.582078+00:00'
[2023-11-30T01:43:41.439+0200] {sql.py:274} INFO - Executing: 
        INSERT INTO measures (timestamp, date, temp, humidity, clouds, wind_speed) VALUES
        (1701301407,
        "2023-11-29 23:43:27",
        -7.35),
        86),
        7),
        3.87);
        
[2023-11-30T01:43:41.452+0200] {base.py:73} INFO - Using connection ID 'airflow_conn' for task execution.
[2023-11-30T01:43:41.521+0200] {base.py:73} INFO - Using connection ID 'airflow_conn' for task execution.
[2023-11-30T01:43:41.524+0200] {sql.py:418} INFO - Running statement: 
        INSERT INTO measures (timestamp, date, temp, humidity, clouds, wind_speed) VALUES
        (1701301407,
        "2023-11-29 23:43:27",
        -7.35),
        86),
        7),
        3.87);
        , parameters: None
[2023-11-30T01:43:41.526+0200] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: near "86": syntax error
[2023-11-30T01:43:41.574+0200] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lviv_weather, task_id=inject_data, execution_date=20231129T234327, start_date=20231129T234340, end_date=20231129T234341
[2023-11-30T01:43:41.592+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task inject_data (near "86": syntax error; 148653)
[2023-11-30T01:43:41.617+0200] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T01:43:41.647+0200] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
