[2023-11-29T22:38:59.752+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lviv_weather.inject_data manual__2023-11-29T20:37:27.921298+00:00 [queued]>
[2023-11-29T22:38:59.757+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lviv_weather.inject_data manual__2023-11-29T20:37:27.921298+00:00 [queued]>
[2023-11-29T22:38:59.758+0200] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-29T22:38:59.771+0200] {taskinstance.py:1382} INFO - Executing <Task(SqliteOperator): inject_data> on 2023-11-29 20:37:27.921298+00:00
[2023-11-29T22:38:59.772+0200] {standard_task_runner.py:57} INFO - Started process 107141 to run task
[2023-11-29T22:38:59.776+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'lviv_weather', 'inject_data', 'manual__2023-11-29T20:37:27.921298+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/lviv_weather.py', '--cfg-path', '/tmp/tmp0f7pepn5']
[2023-11-29T22:38:59.777+0200] {standard_task_runner.py:85} INFO - Job 57: Subtask inject_data
[2023-11-29T22:38:59.803+0200] {task_command.py:416} INFO - Running <TaskInstance: lviv_weather.inject_data manual__2023-11-29T20:37:27.921298+00:00 [running]> on host yurabd.
[2023-11-29T22:38:59.850+0200] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'inject_data', field 'sql'. Template: "\n        INSERT INTO measures (timestamp, temp) VALUES\n        ({{ti.xcom_pull(task_ids='process_data')[0]}},\n        {{str(ti.xcom_pull(task_ids='process_data')[1])}},\n        {{ti.xcom_pull(task_ids='process_data')[2]}});\n        "
Traceback (most recent call last):
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 16, in root
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str' is undefined
[2023-11-29T22:38:59.874+0200] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 16, in root
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str' is undefined
[2023-11-29T22:38:59.900+0200] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lviv_weather, task_id=inject_data, execution_date=20231129T203727, start_date=20231129T203859, end_date=20231129T203859
[2023-11-29T22:38:59.911+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 57 for task inject_data ('str' is undefined; 107141)
[2023-11-29T22:38:59.948+0200] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-29T22:38:59.957+0200] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
