[2023-11-30T03:04:07.968+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lviv_weather.inject_data_Lviv manual__2023-11-30T01:03:57.312815+00:00 [queued]>
[2023-11-30T03:04:07.976+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lviv_weather.inject_data_Lviv manual__2023-11-30T01:03:57.312815+00:00 [queued]>
[2023-11-30T03:04:07.976+0200] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T03:04:07.987+0200] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): inject_data_Lviv> on 2023-11-30 01:03:57.312815+00:00
[2023-11-30T03:04:07.990+0200] {standard_task_runner.py:57} INFO - Started process 167715 to run task
[2023-11-30T03:04:07.994+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'lviv_weather', 'inject_data_Lviv', 'manual__2023-11-30T01:03:57.312815+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/lviv_weather.py', '--cfg-path', '/tmp/tmp_k3vdlma']
[2023-11-30T03:04:07.996+0200] {standard_task_runner.py:85} INFO - Job 161: Subtask inject_data_Lviv
[2023-11-30T03:04:08.051+0200] {task_command.py:416} INFO - Running <TaskInstance: lviv_weather.inject_data_Lviv manual__2023-11-30T01:03:57.312815+00:00 [running]> on host yurabd.
[2023-11-30T03:04:08.367+0200] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='lviv_weather' AIRFLOW_CTX_TASK_ID='inject_data_Lviv' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T01:03:57.312815+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T01:03:57.312815+00:00'
[2023-11-30T03:04:08.368+0200] {sql.py:274} INFO - Executing: 
            INSERT INTO measures (city, timestamp, date, temp, humidity, clouds, wind_speed) VALUES
            (Lviv,
            to_timestamp(1701306237),
            '2023-11-30 01:03:57',
            -7.37,
            87,
            14,
            3.9);
            
[2023-11-30T03:04:08.383+0200] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-11-30T03:04:08.412+0200] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-11-30T03:04:08.421+0200] {sql.py:418} INFO - Running statement: 
            INSERT INTO measures (city, timestamp, date, temp, humidity, clouds, wind_speed) VALUES
            (Lviv,
            to_timestamp(1701306237),
            '2023-11-30 01:03:57',
            -7.37,
            87,
            14,
            3.9);
            , parameters: None
[2023-11-30T03:04:08.421+0200] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "lviv" does not exist
LINE 3:             (Lviv,
                     ^

[2023-11-30T03:04:08.441+0200] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lviv_weather, task_id=inject_data_Lviv, execution_date=20231130T010357, start_date=20231130T010407, end_date=20231130T010408
[2023-11-30T03:04:08.451+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 161 for task inject_data_Lviv (column "lviv" does not exist
LINE 3:             (Lviv,
                     ^
; 167715)
[2023-11-30T03:04:08.488+0200] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T03:04:08.507+0200] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
